# -*- coding: utf-8 -*-
"""web_scraper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gR1PDMuzd_hsd5-Eoy-0xyN9PpzDFwHw
"""

import requests
from bs4 import BeautifulSoup

url = "https://www.indiatoday.in/"

def scrape_headlines(url):
  response = requests.get(url)
  response.raise_for_status()
  soup = BeautifulSoup(response.text, "html.parser")
  headlines = []
  for h2 in soup.find_all('h2'):
    headline = h2.get_text(strip=True)
    if headline:
      headlines.append(headline)

  return headlines

def save_headlines(headlines, filename= "news_headlines.txt"):
  with open(filename, "w", encoding= "utf-8") as f:
    for headline in headlines:
      f.write(headline + "\n")

headlines = scrape_headlines(url)
save_headlines(headlines)
print(f"Scraped {len(headlines)} headlines and saved to 'news_headlines.txt'")